name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 7 * * WED'

jobs:
  CI:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {dockerfile: 'ubuntu',   tag: 'latest'}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker images for Github Container Registry
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/exascaleam/workflows/${{ matrix.config.dockerfile }}:${{ matrix.config.tag }}
          file: docker/${{ matrix.config.dockerfile }}
          build-args: ${{ matrix.config.build_args }}
          pull: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
